version: '3.8'

services:
  digit-caster-fe:
    container_name:   digit-caster-fe
    build: .
    restart: on-failure
    ports:
      - 80:80
    networks:
      - net

  digit-caster-be:
    container_name: digit-caster-be
    image: digit-caster_app-digit-caster:latest
    restart: on-failure
    ports:
      - 9000:9000
    networks:
      - net

networks:
  net:
    name: external_net
