version: '3.8'

services:
  digit-caster-fe:
    container_name: digit-caster-fe
    image: digit-caster-fe:1.0
    build: ./
    restart: on-failure
    volumes:
      - /etc/ssl:/etc/nginx/ssl
    ports:
      - 443:443
    networks:
      - net

  digit-caster-be:
    container_name: digit-caster-be
    image: digit-caster-be:1.0
    restart: on-failure
    ports:
      - 9000:9000
    networks:
      - net

networks:
  net:
    name: external_net
